name: Test workflow publish ###
on:
  push:
    branches:
      # - master - See https://github.com/rancher/dashboard/issues/14230
      - 'release-*'
  pull_request:
    branches:
      - main
      - 'release-*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  a11y-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # - name: Upload report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: accessibility-report
      #     path: base/

      # - name: Unzip report
      #   run: |
      #     unzip *.zip -d cypress/accessibility/html

      - name: Deploy a11y report to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          DEPLOY_ALIAS="pr-${PR_NUMBER}"
          npx netlify deploy \
            --auth $NETLIFY_AUTH_TOKEN \
            --site=$NETLIFY_SITE_ID \
            --dir=base \
            --alias=$DEPLOY_ALIAS

      # - name: Set GitHub Deployment Status
      #   uses: actions/deployment-status@v2.0.0
      #   with:
      #     state: success
      #     environment: pr-${{ github.event.pull_request.number }}
      #     environment_url: https://chipper-paletas-75dfc9.netlify.app/pr-${{ github.event.pull_request.number }}
      
      - name: Create GitHub Deployment and Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;
            const envName = `a11y-pr-${prNumber}`;
            const envUrl = `https://chipper-paletas-75dfc9.netlify.app/pr-${prNumber}`;

            const deployment = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
              required_contexts: [],
              environment: envName,
              auto_merge: false,
              transient_environment: true
            });

            await github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deployment.data.id,
              state: "success",
              environment_url: envUrl,
              log_url: envUrl
            });


        
